import './globals.css'
import '@govbr-ds/core/dist/core.min.css'
import '@fortawesome/fontawesome-free/css/all.min.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import Head from 'next/head'
import { AnaHeader } from '@/components/AnaHeader'
import { AnaFooter } from '@/components/AnaFooter'
import { AnaMenu } from '@/components/AnaMenu'
import { AnaBreadcumb } from '@/components/AnaBreadcumb'

const fontRaleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Padrão Digital de Governo',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdn.dsgovserprodesign.estaleiro.serpro.gov.br/design-system/fonts/rawline/css/rawline.css"
        />
      </Head>
      <body className={fontRaleway.className}>
        <div className="template-base">
          <AnaHeader />
          <main className="d-flex flex-fill mb-5" id="main">
            <div className="container-lg d-flex">
              <div className="row">
                <AnaMenu />
                <div className="col mb-5">
                  <AnaBreadcumb />
                  <div className="main-content pl-sm-3 mt-4" id="main-content">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </main>
          <AnaFooter />
        </div>
      </body>
    </html>
  )
}
